// Code generated by protoc-gen-go. DO NOT EDIT.
// source: syntax.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestArgs struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestArgs) Reset()         { *m = RequestArgs{} }
func (m *RequestArgs) String() string { return proto.CompactTextString(m) }
func (*RequestArgs) ProtoMessage()    {}
func (*RequestArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_syntax_3c8ccd0cbf484067, []int{0}
}
func (m *RequestArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestArgs.Unmarshal(m, b)
}
func (m *RequestArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestArgs.Marshal(b, m, deterministic)
}
func (dst *RequestArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestArgs.Merge(dst, src)
}
func (m *RequestArgs) XXX_Size() int {
	return xxx_messageInfo_RequestArgs.Size(m)
}
func (m *RequestArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RequestArgs proto.InternalMessageInfo

func (m *RequestArgs) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResponseArgs struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseArgs) Reset()         { *m = ResponseArgs{} }
func (m *ResponseArgs) String() string { return proto.CompactTextString(m) }
func (*ResponseArgs) ProtoMessage()    {}
func (*ResponseArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_syntax_3c8ccd0cbf484067, []int{1}
}
func (m *ResponseArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseArgs.Unmarshal(m, b)
}
func (m *ResponseArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseArgs.Marshal(b, m, deterministic)
}
func (dst *ResponseArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseArgs.Merge(dst, src)
}
func (m *ResponseArgs) XXX_Size() int {
	return xxx_messageInfo_ResponseArgs.Size(m)
}
func (m *ResponseArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseArgs proto.InternalMessageInfo

func (m *ResponseArgs) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestArgs)(nil), "proto.RequestArgs")
	proto.RegisterType((*ResponseArgs)(nil), "proto.ResponseArgs")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *RequestArgs, opts ...grpc.CallOption) (*ResponseArgs, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *RequestArgs, opts ...grpc.CallOption) (*ResponseArgs, error) {
	out := new(ResponseArgs)
	err := c.cc.Invoke(ctx, "/proto.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *RequestArgs) (*ResponseArgs, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*RequestArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syntax.proto",
}

func init() { proto.RegisterFile("syntax.proto", fileDescriptor_syntax_3c8ccd0cbf484067) }

var fileDescriptor_syntax_3c8ccd0cbf484067 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xae, 0xcc, 0x2b,
	0x49, 0xac, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xea, 0x5c, 0xdc,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x8e, 0x45, 0xe9, 0xc5, 0x42, 0x12, 0x5c, 0xec, 0xb9,
	0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x92,
	0x06, 0x17, 0x4f, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x7e, 0x95, 0x46, 0x0e, 0x5c,
	0xec, 0xee, 0x45, 0xa9, 0xa9, 0x25, 0xa9, 0x45, 0x42, 0xa6, 0x5c, 0x1c, 0xc1, 0x89, 0x95, 0x1e,
	0xa9, 0x39, 0x39, 0xf9, 0x42, 0x42, 0x10, 0x8b, 0xf5, 0x90, 0xac, 0x93, 0x12, 0x86, 0x8b, 0x21,
	0x4c, 0x56, 0x62, 0x48, 0x62, 0x03, 0x8b, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x20, 0x0e,
	0x70, 0x71, 0xb2, 0x00, 0x00, 0x00,
}
